(*
Defs.inc
--------
Begin: 2008/11/09
Last revision: $Date: 2009-08-08 00:57:36 $ $Author: areeves $
Version: $Revision: 1.3 $
Project: 
Website: 
Author: Aaron Reeves <Aaron.Reeves@colostate.edu>
--------------------------------------------------
Copyright (C) 2008 - 2009 Animal Population Health Institute, Colorado State University

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General
Public License as published by the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.
*)


// The following symbol must be defined for the PDF classes to have access to an SQL database.
//{$DEFINE DATABASE_ENABLED}

// The following symbol must be defined for the PDF classes to generate calculations, instead
// of simply storing parameters.
// (For this project, it should ALWAYS be defined.)
{$DEFINE USE_GSL}

// Define the following symbol to display and use the debugging window.
{$DEFINE DEBUG}






